import { supabase } from './supabase';

const missing=()=>new Error('Supabase is not configured');
export const currentSchoolId=()=>supabase?supabase.rpc('current_school_id').then((r:any)=>({data:{school_id:r.data},error:r.error})):Promise.resolve({data:null,error:missing()});
export const listClasses=()=>supabase?supabase.from('classes').select('id,name,section,room,academic_year_id,created_at').order('name'):Promise.resolve({data:[],error:missing()});
export const createClass=(school_id:string,name:string,section='A',room?:string,academic_year_id?:string)=>supabase?supabase.from('classes').insert({school_id,name,section,room,academic_year_id}).select().single():Promise.reject(missing());
export const updateClass=(id:string,input:{name:string;section:string;room?:string})=>supabase?supabase.from('classes').update(input).eq('id',id).select().single():Promise.reject(missing());
export const deleteClass=(id:string)=>supabase?supabase.from('classes').delete().eq('id',id):Promise.reject(missing());
export const listSubjects=()=>supabase?supabase.from('subjects').select('id,name,code,created_at').order('name'):Promise.resolve({data:[],error:missing()});
export const createSubject=(school_id:string,name:string,code?:string)=>supabase?supabase.from('subjects').insert({school_id,name,code}).select().single():Promise.reject(missing());
export const updateSubject=(id:string,input:{name:string;code?:string})=>supabase?supabase.from('subjects').update(input).eq('id',id).select().single():Promise.reject(missing());
export const deleteSubject=(id:string)=>supabase?supabase.from('subjects').delete().eq('id',id):Promise.reject(missing());
export const listEnrollments=()=>supabase?supabase.from('student_enrollments').select('id,student_id,class_id,roll_number,active,enrolled_at').order('enrolled_at',{ascending:false}):Promise.resolve({data:[],error:missing()});
export const listClassEnrollments=(class_id:string)=>supabase?supabase.from('student_enrollments').select('id,student_id,class_id,roll_number,active,enrolled_at').eq('class_id',class_id).order('roll_number'):Promise.resolve({data:[],error:missing()});
export const enrollStudent=(school_id:string,student_id:string,class_id:string,roll_number?:string)=>supabase?supabase.from('student_enrollments').upsert({school_id,student_id,class_id,roll_number,active:true},{onConflict:'student_id,class_id'}).select().single():Promise.reject(missing());
export const unenrollStudent=(id:string)=>supabase?supabase.from('student_enrollments').update({active:false}).eq('id',id).select().single():Promise.reject(missing());
export const listTeacherAssignments=(class_id?:string)=>{if(!supabase)return Promise.resolve({data:[],error:missing()});let q=supabase.from('teacher_assignments').select('id,teacher_id,class_id,subject_id,created_at').order('created_at',{ascending:false});return class_id?q.eq('class_id',class_id):q};
export const assignTeacher=(school_id:string,teacher_id:string,class_id:string,subject_id:string)=>supabase?supabase.from('teacher_assignments').upsert({school_id,teacher_id,class_id,subject_id},{onConflict:'teacher_id,class_id,subject_id'}).select().single():Promise.reject(missing());
export const unassignTeacher=(id:string)=>supabase?supabase.from('teacher_assignments').delete().eq('id',id):Promise.reject(missing());
export const listAttendance=(date:string)=>supabase?supabase.from('attendance').select('id,student_id,class_id,attendance_date,status,note,marked_by').eq('attendance_date',date):Promise.resolve({data:[],error:missing()});
export const markAttendance=(row:{school_id:string;student_id:string;class_id:string;attendance_date:string;status:string;marked_by:string;note?:string})=>supabase?supabase.from('attendance').upsert(row,{onConflict:'student_id,attendance_date'}).select().single():Promise.reject(missing());
export const listTimetable=()=>supabase?supabase.from('timetable_entries').select('id,class_id,subject_id,teacher_id,weekday,start_time,end_time,room').order('weekday').order('start_time'):Promise.resolve({data:[],error:missing()});
