import React,{useEffect,useState}from'react';
import{Plus,Save,Loader2,AlertCircle,Trophy}from'lucide-react';
import{listExams,createExam,listResults,saveExamResult}from'../lib/academic-workflows';
import{listSubjects,currentSchoolId}from'../lib/academics';
import{listSchoolUsers}from'../lib/platform';

export function ExamsResultsPanel(){
 const[exams,setExams]=useState<any[]>([]),[results,setResults]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[exam,setExam]=useState('');
 const[showExam,setShowExam]=useState(false),[showResult,setShowResult]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const[newExam,setNewExam]=useState({name:'',term:'',exam_date:'',description:''}),[newResult,setNewResult]=useState({student_id:'',subject_id:'',marks:'',max_marks:'100',remarks:''});
 const load=async()=>{setLoading(true);setError('');try{const[e,s,u]=await Promise.all([listExams(),listSubjects(),listSchoolUsers('student')]);if(e.error)throw new Error(e.error.message);if(s.error)throw new Error(s.error.message);if(u.error)throw new Error(u.error.message);setExams(e.data||[]);setSubjects(s.data||[]);setStudents(u.data||[]);if(!exam&&e.data?.[0])setExam(e.data[0].id)}catch(x){setError(x instanceof Error?x.message:'Unable to load exams.')}finally{setLoading(false)}};
 const loadResults=async(id:string)=>{if(!id)return setResults([]);const r=await listResults();if(r.error)setError(r.error.message);else setResults((r.data||[]).filter((x:any)=>x.exam_id===id).map((x:any)=>({...x,_marks:x.marks,_max:x.max_marks||100})))};
 useEffect(()=>{load()},[]);useEffect(()=>{loadResults(exam)},[exam]);
 const saveExam=async(e:React.FormEvent)=>{e.preventDefault();if(!newExam.name.trim()||!newExam.exam_date)return;setSaving(true);setError('');try{const school=await currentSchoolId();if(school.error||!school.data?.school_id)throw new Error(school.error?.message||'School not found.');const r=await createExam({school_id:school.data.school_id,name:newExam.name.trim(),term:newExam.term.trim()||null,exam_date:newExam.exam_date,description:newExam.description.trim()||null,status:'scheduled'});if(r.error)throw new Error(r.error.message);setNewExam({name:'',term:'',exam_date:'',description:''});setShowExam(false);setExam(r.data.id);await load()}catch(x){setError(x instanceof Error?x.message:'Unable to create exam.')}finally{setSaving(false)}};
 const saveResult=async(r:any)=>{const marks=Number(r._marks),max=Number(r._max)||100;if(!Number.isFinite(marks)||marks<0||marks>max){setError(`Enter a mark from 0 to ${max}.`);return}setSaving(true);try{const x=await saveExamResult({id:r.id,exam_id:r.exam_id,student_id:r.student_id,subject_id:r.subject_id,marks,max_marks:max,remarks:r.remarks||null});if(x.error)throw new Error(x.error.message);setResults(p=>p.map(y=>y.id===r.id?{...y,marks,max_marks:max}:y))}catch(e){setError(e instanceof Error?e.message:'Unable to save result.')}finally{setSaving(false)}};
 const addResult=async(e:React.FormEvent)=>{e.preventDefault();if(!exam||!newResult.student_id||!newResult.subject_id)return;const marks=Number(newResult.marks),max=Number(newResult.max_marks)||100;if(!Number.isFinite(marks)||marks<0||marks>max){setError(`Enter a mark from 0 to ${max}.`);return}setSaving(true);setError('');try{const school=await currentSchoolId();if(school.error||!school.data?.school_id)throw new Error(school.error?.message||'School not found.');const x=await saveExamResult({school_id:school.data.school_id,exam_id:exam,student_id:newResult.student_id,subject_id:newResult.subject_id,marks,max_marks:max,remarks:newResult.remarks.trim()||null});if(x.error)throw new Error(x.error.message);setNewResult({student_id:'',subject_id:'',marks:'',max_marks:'100',remarks:''});setShowResult(false);await loadResults(exam)}catch(e){setError(e instanceof Error?e.message:'Unable to add result.')}finally{setSaving(false)}};
 return <section className="ops"><div className="ops-head"><div><span className="eyebrow">ASSESSMENT</span><h2>Exams & Results</h2><p>Schedule exams and manage student results.</p></div><div style={{display:'flex',gap:8}}><button className="ghost" onClick={()=>setShowResult(true)} disabled={!exam}><Plus size={15}/> Add result</button><button className="primary" onClick={()=>setShowExam(true)}><Plus size={15}/> Add exam</button></div></div>{error&&<div className="ops-error"><AlertCircle size={15}/>{error}</div>}{loading?<div className="empty-state"><Loader2 className="spin"/> Loading…</div>:<><div className="attendance-controls"><label>Exam<select value={exam} onChange={e=>setExam(e.target.value)}><option value="">Select exam</option>{exams.map(x=><option key={x.id} value={x.id}>{x.name||x.title} · {x.exam_date||'No date'}</option>)}</select></label></div>{!exam?<div className="empty-state"><Trophy size={24}/><b>Select an exam</b></div>:results.length===0?<div className="empty-state"><Trophy size={24}/><b>No results recorded</b><span>Use Add result to enter the first result.</span></div>:<div className="ops-table">{results.map(r=><div className="ops-row" key={r.id}><div><b>{students.find(s=>s.id===r.student_id)?.full_name||r.student_id}</b><small>{subjects.find(s=>s.id===r.subject_id)?.name||r.subject_id}</small></div><label>Marks<input type="number" min="0" max={r._max} value={r._marks??''} onChange={e=>setResults(p=>p.map(x=>x.id===r.id?{...x,_marks:e.target.value}:x))}/></label><span>/ {r._max}</span><button className="icon-btn" disabled={saving} onClick={()=>saveResult(r)}>{saving?<Loader2 className="spin" size={15}/>:<Save size={15}/>}</button></div>)}</div>}</>}
 {showExam&&<div className="modal-back"><form className="login" onSubmit={saveExam}><button type="button" className="x" onClick={()=>setShowExam(false)}>×</button><h2>New exam</h2><label>Name<input required value={newExam.name} onChange={e=>setNewExam({...newExam,name:e.target.value})}/></label><label>Term<input value={newExam.term} onChange={e=>setNewExam({...newExam,term:e.target.value})}/></label><label>Exam date<input required type="date" value={newExam.exam_date} onChange={e=>setNewExam({...newExam,exam_date:e.target.value})}/></label><label>Description<textarea value={newExam.description} onChange={e=>setNewExam({...newExam,description:e.target.value})}/></label><button className="primary big full" disabled={saving}>{saving?'Saving…':'Schedule exam'}</button></form></div>}
 {showResult&&<div className="modal-back"><form className="login" onSubmit={addResult}><button type="button" className="x" onClick={()=>setShowResult(false)}>×</button><h2>Add result</h2><label>Student<select required value={newResult.student_id} onChange={e=>setNewResult({...newResult,student_id:e.target.value})}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Subject<select required value={newResult.subject_id} onChange={e=>setNewResult({...newResult,subject_id:e.target.value})}><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}{s.code?` (${s.code})`:''}</option>)}</select></label><label>Marks<input required type="number" min="0" value={newResult.marks} onChange={e=>setNewResult({...newResult,marks:e.target.value})}/></label><label>Maximum marks<input required type="number" min="1" value={newResult.max_marks} onChange={e=>setNewResult({...newResult,max_marks:e.target.value})}/></label><label>Remarks<textarea value={newResult.remarks} onChange={e=>setNewResult({...newResult,remarks:e.target.value})}/></label><button className="primary big full" disabled={saving}>{saving?'Saving…':'Save result'}</button></form></div>}
 </section>;
}
