import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Loader2, PlusCircle, RefreshCw, Wallet, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

type ChallanStatus = 'pending' | 'submitted' | 'verified' | 'rejected';
interface Challan { id:string; student_id:string; school_id:string; month:string; amount:number; status:ChallanStatus; transaction_reference:string|null; payment_proof_url:string|null; created_at:string; student?:{full_name:string|null}; }
const money=(n:number)=>new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:0}).format(n);

export function FeeManagement(){
 const [schoolId,setSchoolId]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[amount,setAmount]=useState(''),[rows,setRows]=useState<Challan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState<'overview'|'verification'>('overview'),[rejecting,setRejecting]=useState<Challan|null>(null),[rejectNote,setRejectNote]=useState('');
 const load=async()=>{setLoading(true);setError('');try{if(!supabase)throw new Error('Supabase is not configured.');const {data:user,error:ue}=await supabase.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in as an administrator.');const {data:p,error:pe}=await supabase.from('profiles').select('school_id,role').eq('id',user.id).maybeSingle();if(pe)throw pe;if(!p?.school_id||!['admin','super_admin'].includes(p.role))throw new Error('You do not have permission to manage fees.');setSchoolId(p.school_id);const {data,error}=await supabase.from('fee_challans').select('id,student_id,school_id,month,amount,status,transaction_reference,payment_proof_url,created_at,student:profiles!fee_challans_student_id_fkey(full_name)').eq('school_id',p.school_id).order('created_at',{ascending:false});if(error)throw error;setRows((data||[]) as unknown as Challan[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load fee challans.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const verified=rows.filter(x=>x.status==='verified'),open=rows.filter(x=>x.status==='pending'||x.status==='submitted'),paid=new Set(verified.map(x=>x.student_id)),students=new Set(rows.map(x=>x.student_id));return{received:verified.reduce((s,x)=>s+Number(x.amount||0),0),pending:open.reduce((s,x)=>s+Number(x.amount||0),0),paid:paid.size,unpaid:Math.max(0,students.size-paid.size),queue:rows.filter(x=>x.status==='submitted').length}},[rows]);
 const generate=async()=>{setError('');setMessage('');const value=Number(amount);if(!month||!Number.isFinite(value)||value<=0){setError('Select a month and enter a fee amount greater than zero.');return}setSaving(true);try{if(!supabase||!schoolId)throw new Error('School context is unavailable.');const {data:students,error}=await supabase.from('profiles').select('id').eq('school_id',schoolId).eq('role','student');if(error)throw error;if(!students?.length)throw new Error('No students were found for this school.');const {error:ie}=await supabase.from('fee_challans').upsert(students.map(s=>({student_id:s.id,school_id:schoolId,month,amount:value,status:'pending' as const})),{onConflict:'student_id,month',ignoreDuplicates:true});if(ie)throw ie;setMessage(`${students.length} monthly challans generated.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to generate challans.')}finally{setSaving(false)}};
 const approve=async(c:Challan)=>{setError('');try{if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.from('fee_challans').update({status:'verified'}).eq('id',c.id).eq('school_id',schoolId).eq('status','submitted').select('id,status').maybeSingle();if(error)throw error;if(!data)throw new Error('Challan is no longer awaiting verification.');setRows(r=>r.map(x=>x.id===c.id?{...x,status:'verified'}:x));setMessage('Payment verified successfully.')}catch(e){setError(e instanceof Error?e.message:'Unable to verify payment.')}};
 const reject=async()=>{if(!rejecting)return;setSaving(true);setError('');try{if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.from('fee_challans').update({status:'pending',payment_proof_url:rejectNote.trim()||rejecting.payment_proof_url}).eq('id',rejecting.id).eq('school_id',schoolId).eq('status','submitted').select('id,status').maybeSingle();if(error)throw error;if(!data)throw new Error('Challan is no longer awaiting verification.');setRows(r=>r.map(x=>x.id===rejecting.id?{...x,status:'pending'}:x));setRejecting(null);setRejectNote('');setMessage('Payment rejected and returned to pending.')}catch(e){setError(e instanceof Error?e.message:'Unable to reject payment.')}finally{setSaving(false)}};
 const queue=rows.filter(x=>x.status==='submitted');
 return <section className="ops"><div className="ops-head"><div><span className="eyebrow">FINANCE</span><h2>Fee management</h2><p>Generate monthly challans and verify online payments.</p></div><button className="primary" onClick={load} disabled={loading}><RefreshCw size={15}/> Refresh</button></div>{error&&<div className="ops-error"><AlertCircle size={15}/>{error}</div>}{message&&<div className="ops-success"><CheckCircle2 size={15}/>{message}</div>}
 <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='verification'?'active':''} onClick={()=>setTab('verification')}>Verification Queue {stats.queue>0&&<b>{stats.queue}</b>}</button></div>
 {tab==='overview'?<><div className="stats-grid"><div className="stat-card"><span>Total Fees Received</span><b>{money(stats.received)}</b></div><div className="stat-card"><span>Total Fees Pending</span><b>{money(stats.pending)}</b></div><div className="stat-card"><span>Paid Students</span><b>{stats.paid}</b></div><div className="stat-card"><span>Unpaid Students</span><b>{stats.unpaid}</b></div></div><div className="panel" style={{marginTop:18}}><div className="panel-head"><b><Wallet size={16}/> Generate monthly challans</b></div><div className="form-grid"><label>Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Amount (PKR)<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. 15000"/></label><div style={{display:'flex',alignItems:'end'}}><button className="primary" onClick={generate} disabled={saving}>{saving?<><Loader2 size={15} className="spin"/> Generating…</>:<><PlusCircle size={15}/> Generate Monthly Challans</>}</button></div></div></div></>:<div className="ops-table" style={{marginTop:18}}>{loading?<div className="empty-state"><Loader2 className="spin"/> Loading verification queue…</div>:queue.length===0?<div className="empty-state"><CheckCircle2 size={24}/><b>Verification queue is clear</b><small>No submitted payments are waiting for review.</small></div>:<>{queue.map(c=><div className="ops-row" key={c.id}><div><b>{c.student?.full_name||c.student_id}</b><small>{c.month} · {money(Number(c.amount))}</small></div><div><b>Transaction reference</b><small>{c.transaction_reference||'Not provided'}</small></div><div style={{display:'flex',gap:8,justifyContent:'flex-end'}}><button className="primary" onClick={()=>approve(c)} disabled={saving}><CheckCircle2 size={15}/> Approve</button><button className="secondary" onClick={()=>{setRejecting(c);setRejectNote('')}} disabled={saving}><X size={15}/> Reject</button></div></div>)}</>}</div>}
 {rejecting&&<div className="modal-back"><div className="login"><button className="x" onClick={()=>setRejecting(null)}>×</button><h2>Reject payment</h2><p>{rejecting.student?.full_name||rejecting.student_id} · {rejecting.month} · {money(Number(rejecting.amount))}</p><label>Rejection note<textarea rows={4} value={rejectNote} onChange={e=>setRejectNote(e.target.value)} placeholder="Optional reason for rejection"/></label><button className="primary big full" onClick={reject} disabled={saving}>{saving?<><Loader2 size={15} className="spin"/> Rejecting…</>:<>Reject Payment</>}</button></div></div>}
 </section>;
}
