import React,{useEffect,useState}from'react';import{BookOpen,ClipboardCheck,GraduationCap,Users,Plus,CalendarDays,X,Loader2}from'lucide-react';import{listSchoolUsers,createSchoolUser}from'../lib/platform';import{listClasses,listSubjects}from'../lib/academics';

type Role='teacher'|'student'|'parent';

export function SchoolOperations(){const[tab,setTab]=useState<'people'|'classes'|'subjects'|'attendance'>('people');const[role,setRole]=useState<Role>('student');const[data,setData]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[showAdd,setShowAdd]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');const[form,setForm]=useState({full_name:'',email:'',password:'',phone:''});

const load=async()=>{setLoading(true);setError('');let r:any;if(tab==='people')r=await listSchoolUsers(role);else if(tab==='classes')r=await listClasses();else if(tab==='subjects')r=await listSubjects();else r={data:[]};if(r.error)setError(r.error.message||'Unable to load school data.');setData(r.data||[]);setLoading(false)};
useEffect(()=>{let live=true;setLoading(true);const run=async()=>{let r:any;if(tab==='people')r=await listSchoolUsers(role);else if(tab==='classes')r=await listClasses();else if(tab==='subjects')r=await listSubjects();else r={data:[]};if(live){if(r.error)setError(r.error.message||'Unable to load school data.');setData(r.data||[]);setLoading(false)}};run();return()=>{live=false}},[tab,role]);

const openAdd=()=>{setError('');setSuccess('');setForm({full_name:'',email:'',password:'',phone:''});setShowAdd(true)};
const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{const r=await createSchoolUser({role,full_name:form.full_name,email:form.email,password:form.password,phone:form.phone||undefined});if(r.error)throw new Error(r.error.message||'Unable to create user.');setSuccess(`${role.charAt(0).toUpperCase()+role.slice(1)} created successfully.`);setShowAdd(false);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to create user.')}finally{setSaving(false)}};

const labels={people:'People',classes:'Classes',subjects:'Subjects',attendance:'Attendance'};const addLabel=tab==='people'?role:tab==='classes'?'class':tab==='subjects'?'subject':'attendance';
return <div className="ops"><div className="ops-head"><div><span className="eyebrow">SCHOOL OPERATIONS</span><h2>Manage your school</h2><p>Teachers, students, parents, classes and attendance in one workspace.</p></div><button className="primary" onClick={openAdd}><Plus size={15}/> Add {addLabel}</button></div>{success&&<div className="ops-success" role="status">{success}</div>}{error&&<div className="ops-error" role="alert">{error}</div>}<div className="ops-tabs">{(['people','classes','subjects','attendance'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setSuccess('');setError('')}}>{t==='people'?<Users size={15}/>:t==='classes'?<GraduationCap size={15}/>:t==='subjects'?<BookOpen size={15}/>:<ClipboardCheck size={15}/>} {labels[t]}</button>)}</div>{tab==='people'&&<div className="role-switch">{(['student','teacher','parent'] as const).map(r=><button key={r} className={role===r?'selected':''} onClick={()=>{setRole(r);setSuccess('');setError('')}}>{r}</button>)}</div>}<div className="ops-panel">{loading?<div className="empty-state">Loading school data…</div>:data.length===0?<div className="empty-state"><CalendarDays size={22}/><b>No records yet</b><span>Start adding your school data and it will appear here.</span></div>:<div className="ops-table">{data.map((x)=><div className="ops-row" key={x.id}><div><b>{x.full_name||x.name}</b><small>{x.email||x.code||x.section||'School record'}</small></div><span>{x.role||x.section||x.status||''}</span><small>{x.created_at?new Date(x.created_at).toLocaleDateString():''}</small></div>)}</div>}</div>{showAdd&&tab==='people'&&<div className="modal-back" role="dialog" aria-modal="true"><form className="login" onSubmit={submit}><button type="button" className="x" onClick={()=>setShowAdd(false)} aria-label="Close"><X size={18}/></button><h2>Add {role}</h2><p>Create a real {role} account in this school workspace.</p><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="Full name"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="person@school.com"/></label><label>Temporary password<input required minLength={10} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 10 characters"/></label><label>Phone <span>(optional)</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+92..."/></label><button disabled={saving} type="submit" className="primary big full">{saving?<><Loader2 size={16} className="spin"/> Creating…</>:<>Create {role}</>}</button></form></div>}</div>}
