import React,{useEffect,useMemo,useState}from'react';
import{Check,CheckCircle2,Clock,LogOut,Plus,Send,UserX,AlertCircle}from'lucide-react';
import{useAuth}from'../context/AuthContext';
import{listAssignments,createAssignment,listSubmissions,gradeSubmission,listExams,createExam,listAnnouncements,createAnnouncement}from'../lib/academic-workflows';
import{getTodayTimetable}from'../lib/timetable';
import{supabase}from'../lib/supabase';
import{currentSchoolId,listTeacherAssignments,listClasses,listClassEnrollments,listAttendance,markAttendance}from'../lib/academics';

type Row=Record<string,any>;
const card=(title:string,value:number)=><div className="stat-card"><span>{title}</span><strong>{value}</strong><small>{supabase?'Live data':'Demo preview'}</small></div>;

export function TeacherPortal(){
 const{signOut}=useAuth();
 const[assignments,setAssignments]=useState<Row[]>([]),[submissions,setSubmissions]=useState<Row[]>([]),[exams,setExams]=useState<Row[]>([]),[announcements,setAnnouncements]=useState<Row[]>([]),[schedule,setSchedule]=useState<Row[]>([]),[teacherAssignments,setTeacherAssignments]=useState<Row[]>([]),[classes,setClasses]=useState<Row[]>([]),[students,setStudents]=useState<Row[]>([]),[attendance,setAttendance]=useState<Row[]>([]);
 const[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const[tab,setTab]=useState<'overview'|'attendance'>('overview'),[attendanceDate,setAttendanceDate]=useState(()=>new Date().toISOString().slice(0,10)),[selectedClass,setSelectedClass]=useState('');
 const[gradeRow,setGradeRow]=useState<Row|null>(null),[gradeMarks,setGradeMarks]=useState(''),[gradeFeedback,setGradeFeedback]=useState('');
 const[showAssignment,setShowAssignment]=useState(false),[showExam,setShowExam]=useState(false),[showAnnouncement,setShowAnnouncement]=useState(false);
 const[assignment,setAssignment]=useState({title:'',description:'',due_date:'',max_marks:'100',class_id:'',subject_id:''}),[exam,setExam]=useState({name:'',term:'',exam_date:'',description:''}),[announcement,setAnnouncement]=useState({title:'',body:'',audience:'all'});

 const assignedClassIds=useMemo(()=>new Set(teacherAssignments.map(x=>x.class_id)),[teacherAssignments]);
 const assignedOptions=teacherAssignments.map(x=>({id:`${x.class_id}:${x.subject_id}`,class_id:x.class_id,subject_id:x.subject_id,label:`${classes.find(c=>c.id===x.class_id)?.name||'Class'}${classes.find(c=>c.id===x.class_id)?.section?` - ${classes.find(c=>c.id===x.class_id)?.section}`:''} · ${x.subject?.name||x.subject_id}`}));

 const load=async()=>{setLoading(true);setError('');setSuccess('');if(!supabase){setAssignments([{id:'demo-a1',title:'Algebra practice',description:'Complete the algebra worksheet.',due_date:'2026-08-28',max_marks:100,status:'published'}]);setSubmissions([{id:'demo-s1',student_id:'Demo Student',submitted_at:new Date().toISOString(),marks:86,max_marks:100,status:'submitted'}]);setExams([{id:'demo-e1',name:'Mid Term Mathematics',term:'Term 1',exam_date:'2026-09-10',status:'scheduled'}]);setAnnouncements([{id:'demo-n1',title:'Parent meeting',body:'Parent meeting Friday at 10:00.',audience:'all'}]);setLoading(false);return}
 try{const u=await supabase.auth.getUser();if(!u.data.user)throw new Error('Please sign in again.');const[a,s,e,n,t,ta,c]=await Promise.all([listAssignments(),listSubmissions(),listExams(),listAnnouncements(),getTodayTimetable(),listTeacherAssignments(),listClasses()]);const failed=[a,s,e,n,t,ta,c].find(x=>x.error);if(failed?.error)throw failed.error;setAssignments(a.data||[]);setSubmissions(s.data||[]);setExams(e.data||[]);setAnnouncements(n.data||[]);setSchedule((t.data||[]).filter((x:any)=>x.teacher_id===u.data.user.id));setTeacherAssignments((ta.data||[]).filter((x:any)=>x.teacher_id===u.data.user.id));setClasses(c.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load teacher workspace.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);

 const loadRoster=async()=>{if(!supabase||!selectedClass)return;setBusy(true);try{const[e,p]=await Promise.all([listClassEnrollments(selectedClass),supabase.from('profiles').select('id,full_name,phone').eq('school_id',(await currentSchoolId()).data?.school_id).eq('role','student')]);if(e.error)throw e.error;if(p.error)throw p.error;const roster=(e.data||[]).map((x:any)=>({...x,student:p.data?.find((s:any)=>s.id===x.student_id)})).filter((x:any)=>x.student);setStudents(roster);const a=await listAttendance(attendanceDate);if(a.error)throw a.error;const existing=(a.data||[]).filter((x:any)=>x.class_id===selectedClass);setAttendance(roster.map((x:any)=>{const old=existing.find((r:any)=>r.student_id===x.student_id);return{student_id:x.student_id,class_id:selectedClass,attendance_date:attendanceDate,status:old?.status||'present',note:old?.note||''}}))}catch(e){setError(e instanceof Error?e.message:'Unable to load class roster.')}finally{setBusy(false)}};
 useEffect(()=>{if(tab==='attendance'&&selectedClass)loadRoster()},[tab,selectedClass,attendanceDate]);

 const schoolId=async()=>{const s=await currentSchoolId();if(s.error||!s.data?.school_id)throw new Error(s.error?.message||'School not found.');return s.data.school_id};
 const saveAssignment=async(e:React.FormEvent)=>{e.preventDefault();if(!assignment.title.trim()||!assignment.class_id||!assignment.subject_id)return;setBusy(true);setError('');try{const sid=await schoolId();const u=await supabase!.auth.getUser();const r=await createAssignment({school_id:sid,created_by:u.data.user?.id,title:assignment.title.trim(),description:assignment.description.trim()||null,class_id:assignment.class_id,subject_id:assignment.subject_id,due_date:assignment.due_date||null,max_marks:Number(assignment.max_marks)||100,status:'published'});if(r.error)throw r.error;setShowAssignment(false);setAssignment({title:'',description:'',due_date:'',max_marks:'100',class_id:'',subject_id:''});setSuccess('Assignment published.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create assignment.')}finally{setBusy(false)}};
 const saveExam=async(e:React.FormEvent)=>{e.preventDefault();if(!exam.name.trim())return;setBusy(true);setError('');try{const sid=await schoolId();const r=await createExam({school_id:sid,name:exam.name.trim(),term:exam.term.trim()||null,exam_date:exam.exam_date||null,description:exam.description.trim()||null,status:'scheduled'});if(r.error)throw r.error;setShowExam(false);setExam({name:'',term:'',exam_date:'',description:''});setSuccess('Exam scheduled.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create exam.')}finally{setBusy(false)}};
 const saveAnnouncement=async(e:React.FormEvent)=>{e.preventDefault();if(!announcement.title.trim()||!announcement.body.trim())return;setBusy(true);setError('');try{const sid=await schoolId();const u=await supabase!.auth.getUser();const r=await createAnnouncement({school_id:sid,created_by:u.data.user?.id||null,title:announcement.title.trim(),body:announcement.body.trim(),audience:announcement.audience,published:true});if(r.error)throw r.error;setShowAnnouncement(false);setAnnouncement({title:'',body:'',audience:'all'});setSuccess('Announcement published.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to publish announcement.')}finally{setBusy(false)}};
 const saveGrade=async(e:React.FormEvent)=>{e.preventDefault();if(!gradeRow)return;const n=Number(gradeMarks),max=Number(gradeRow.max_marks||100);if(!Number.isFinite(n)||n<0||n>max){setError(`Enter a mark from 0 to ${max}.`);return}setBusy(true);setError('');try{const r=await gradeSubmission(gradeRow.id,n,gradeFeedback.trim());if(r.error)throw r.error;setGradeRow(null);setGradeMarks('');setGradeFeedback('');setSuccess('Submission graded.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to grade submission.')}finally{setBusy(false)}};
 const setStatus=(student_id:string,status:string)=>setAttendance(rows=>rows.map(r=>r.student_id===student_id?{...r,status}:r));
 const saveAttendance=async()=>{if(!supabase||!selectedClass||!attendance.length)return;setBusy(true);setError('');try{const sid=await schoolId();const u=await supabase.auth.getUser();if(!u.data.user)throw new Error('Please sign in again.');for(const row of attendance){const r=await markAttendance({school_id:sid,student_id:row.student_id,class_id:selectedClass,attendance_date:attendanceDate,status:row.status,marked_by:u.data.user.id,note:row.note||undefined});if(r.error)throw r.error}setSuccess(`Attendance saved for ${attendance.length} students.`);await loadRoster()}catch(e){setError(e instanceof Error?e.message:'Unable to save attendance.')}finally{setBusy(false)}};

 if(loading)return <div className="empty-state">Loading teacher workspace…</div>;
 return <div className="teacher-portal"><header className="dash-header"><div><span className="eyebrow">TEACHER PORTAL</span><h1>Teacher workspace</h1><p>Classes, attendance, assignments, grading, exams and communication.</p></div><button className="ghost" onClick={()=>signOut()}><LogOut size={16}/> Sign out</button></header>
 {error&&<div className="ops-error" role="alert">{error}</div>}{success&&<div className="ops-success" role="status">{success}</div>}
 <div className="ops-tabs" style={{marginBottom:16}}><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='attendance'?'active':''} onClick={()=>setTab('attendance')}>Attendance</button></div>
 {tab==='overview'?<><div className="stat-grid">{card('Assignments',assignments.length)}{card('Pending grading',submissions.filter(x=>x.status!=='graded').length)}{card('Exams',exams.length)}{card('Announcements',announcements.length)}</div>
 <div className="dash-grid"><div className="panel"><div className="panel-head"><b>Today's timetable</b><span>My classes</span></div>{schedule.length?schedule.map(x=><div className="class-row" key={x.id}><b>{x.start_time?.slice(0,5)} {x.subjects?.name||'Class'}</b><small>{x.room||x.classes?.name||'—'}{x.classes?.section?` · ${x.classes.section}`:''}</small></div>):<div className="empty-state">No classes scheduled today.</div>}</div><div className="panel"><div className="panel-head"><b>Quick actions</b></div><div style={{padding:16,display:'flex',gap:10,flexWrap:'wrap'}}><button className="primary" disabled={!supabase||!assignedOptions.length} onClick={()=>setShowAssignment(true)}><Plus size={15}/> Assignment</button><button className="ghost" disabled={!supabase} onClick={()=>setShowExam(true)}><Plus size={15}/> Exam</button><button className="ghost" disabled={!supabase} onClick={()=>setShowAnnouncement(true)}><Send size={15}/> Announcement</button></div>{!assignedOptions.length&&supabase&&<small style={{display:'block',padding:'0 16px 16px',color:'#64748b'}}>Ask an administrator to assign your classes and subjects first.</small>}</div></div>
 <div className="panel"><div className="panel-head"><b>My assignments</b><button className="primary" disabled={!supabase||!assignedOptions.length} onClick={()=>setShowAssignment(true)}><Plus size={14}/> New</button></div>{assignments.length?assignments.map(x=><div className="class-row" key={x.id}><div><b>{x.title}</b><small>{x.description||'No description'} · Due {x.due_date||'No due date'}</small></div><span>{x.status}</span></div>):<div className="empty-state">No assignments yet.</div>}</div>
 <div className="panel"><div className="panel-head"><b>Submissions to grade</b><span>{submissions.filter(x=>x.status!=='graded').length} pending</span></div>{submissions.length?submissions.map(x=><div className="class-row" key={x.id}><div><b>{x.student_id||'Student'}</b><small>{x.submitted_at?new Date(x.submitted_at).toLocaleString():'Not submitted'}{x.content?` · ${x.content.slice(0,80)}`:''}</small></div>{x.status==='graded'?<span><CheckCircle2 size={14}/> {x.marks}</span>:<button className="ghost" disabled={busy||!supabase} onClick={()=>{setGradeRow(x);setGradeMarks(String(x.marks??''));setGradeFeedback(x.feedback||'')}}>Grade</button>}</div>):<div className="empty-state">No submissions yet.</div>}</div>
 <div className="panel"><div className="panel-head"><b>Exams</b><button className="ghost" disabled={!supabase} onClick={()=>setShowExam(true)}><Plus size={14}/> New</button></div>{exams.length?exams.map(x=><div className="class-row" key={x.id}><b>{x.name}</b><small>{x.term||'—'} · {x.exam_date||'No date'}</small></div>):<div className="empty-state">No exams scheduled.</div>}</div>
 <div className="panel"><div className="panel-head"><b>Announcements</b><button className="ghost" disabled={!supabase} onClick={()=>setShowAnnouncement(true)}><Plus size={14}/> New</button></div>{announcements.slice(0,5).map(x=><div className="class-row" key={x.id}><div><b>{x.title}</b><small>{x.body}</small></div><span>{x.audience}</span></div>)}{!announcements.length&&<div className="empty-state">No announcements yet.</div>}</div></>:<div className="panel"><div className="panel-head"><b>Class attendance</b><span>Teacher scoped</span></div><div className="attendance-controls"><label>Class<select value={selectedClass} onChange={e=>setSelectedClass(e.target.value)}><option value="">Select assigned class</option>{[...assignedClassIds].map(id=>{const c=classes.find(x=>x.id===id);return <option key={id} value={id}>{c?.name||id}{c?.section?` - ${c.section}`:''}</option>})}</select></label><label>Date<input type="date" value={attendanceDate} onChange={e=>setAttendanceDate(e.target.value)}/></label><button className="primary" disabled={busy||!selectedClass||!students.length} onClick={saveAttendance}>{busy?'Saving…':<><Check size={15}/> Save attendance</>}</button></div>{!selectedClass?<div className="empty-state"><AlertCircle size={22}/><b>Select one of your assigned classes.</b></div>:students.length?<div className="attendance-list">{attendance.map(r=>{const s=students.find(x=>x.student_id===r.student_id)?.student;return <div className="attendance-row" key={r.student_id}><div><b>{s?.full_name||r.student_id}</b><small>{r.status}</small></div><div className="attendance-actions"><button className={r.status==='present'?'selected':''} onClick={()=>setStatus(r.student_id,'present')}><Check size={14}/> Present</button><button className={r.status==='absent'?'selected':''} onClick={()=>setStatus(r.student_id,'absent')}><UserX size={14}/> Absent</button><button className={r.status==='late'?'selected':''} onClick={()=>setStatus(r.student_id,'late')}><Clock size={14}/> Late</button></div></div>})}</div>:<div className="empty-state"><AlertCircle size={22}/><b>No enrolled students in this class.</b></div>}</div>}
 {gradeRow&&<div className="modal-back"><form className="login" onSubmit={saveGrade}><button type="button" className="x" onClick={()=>setGradeRow(null)}>×</button><h2>Grade submission</h2><p>{gradeRow.student_id||'Student'}</p><label>Marks<input required type="number" min="0" max={gradeRow.max_marks||100} step="0.01" value={gradeMarks} onChange={e=>setGradeMarks(e.target.value)}/></label><label>Feedback<textarea rows={6} value={gradeFeedback} onChange={e=>setGradeFeedback(e.target.value)}/></label><button className="primary big full" disabled={busy}>{busy?'Saving…':'Save grade'}</button></form></div>}
 {showAssignment&&<div className="modal-back"><form className="login" onSubmit={saveAssignment}><button type="button" className="x" onClick={()=>setShowAssignment(false)}>×</button><h2>New assignment</h2><label>Class & subject<select required value={assignment.class_id&&assignment.subject_id?`${assignment.class_id}:${assignment.subject_id}`:''} onChange={e=>{const [class_id,subject_id]=e.target.value.split(':');setAssignment({...assignment,class_id,subject_id})}}><option value="">Select assigned class/subject</option>{assignedOptions.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>Title<input required value={assignment.title} onChange={e=>setAssignment({...assignment,title:e.target.value})}/></label><label>Description<textarea value={assignment.description} onChange={e=>setAssignment({...assignment,description:e.target.value})}/></label><label>Due date<input type="date" value={assignment.due_date} onChange={e=>setAssignment({...assignment,due_date:e.target.value})}/></label><label>Maximum marks<input type="number" min="1" value={assignment.max_marks} onChange={e=>setAssignment({...assignment,max_marks:e.target.value})}/></label><button className="primary big full" disabled={busy}>{busy?'Publishing…':'Publish assignment'}</button></form></div>}
 {showExam&&<div className="modal-back"><form className="login" onSubmit={saveExam}><button type="button" className="x" onClick={()=>setShowExam(false)}>×</button><h2>New exam</h2><label>Name<input required value={exam.name} onChange={e=>setExam({...exam,name:e.target.value})}/></label><label>Term<input value={exam.term} onChange={e=>setExam({...exam,term:e.target.value})}/></label><label>Exam date<input type="date" value={exam.exam_date} onChange={e=>setExam({...exam,exam_date:e.target.value})}/></label><label>Description<textarea value={exam.description} onChange={e=>setExam({...exam,description:e.target.value})}/></label><button className="primary big full" disabled={busy}>{busy?'Saving…':'Schedule exam'}</button></form></div>}
 {showAnnouncement&&<div className="modal-back"><form className="login" onSubmit={saveAnnouncement}><button type="button" className="x" onClick={()=>setShowAnnouncement(false)}>×</button><h2>New announcement</h2><label>Title<input required value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></label><label>Message<textarea required rows={6} value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/></label><label>Audience<select value={announcement.audience} onChange={e=>setAnnouncement({...announcement,audience:e.target.value})}><option value="all">Everyone</option><option value="students">Students</option><option value="parents">Parents</option><option value="teachers">Teachers</option></select></label><button className="primary big full" disabled={busy}>{busy?'Publishing…':'Publish announcement'}</button></form></div>}
 </div>;
}
