import { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import { BarChart3, BookOpen, Building2, CalendarDays, CheckCircle2, ChevronRight, GraduationCap, LayoutDashboard, LogOut, Menu, Search, Shield, Users, X } from 'lucide-react';

type Role = 'super_admin' | 'admin' | 'teacher' | 'student' | 'parent';
type Profile = { id:string; full_name?:string|null; email?:string|null; phone?:string|null; role?:Role|null; status?:string|null; school_id?:string|null; created_at?:string|null };

type NavItem = { id:string; label:string; icon:typeof LayoutDashboard };
const nav:NavItem[] = [
  {id:'dashboard',label:'Dashboard',icon:LayoutDashboard},
  {id:'admins',label:'Admin Management',icon:Shield},
  {id:'schools',label:'Schools',icon:Building2},
  {id:'people',label:'People',icon:Users},
  {id:'academics',label:'Academics',icon:GraduationCap},
  {id:'attendance',label:'Attendance',icon:CheckCircle2},
  {id:'grades',label:'Grades & Exams',icon:BarChart3},
  {id:'calendar',label:'Timetable',icon:CalendarDays},
];

function initials(name?:string|null){ return (name||'User').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(); }

export default function App(){
  const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<Profile|null>(null); const [loading,setLoading]=useState(true); const [login,setLogin]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{ let alive=true; supabase.auth.getSession().then(async ({data})=>{ if(!alive)return; setSession(data.session); if(data.session) setProfile(await loadProfile(data.session.user.id)); setLoading(false); }); const {data:{subscription}}=supabase.auth.onAuthStateChange(async(_e,s)=>{ setSession(s); setProfile(s?await loadProfile(s.user.id):null); }); return()=>{alive=false;subscription.unsubscribe()}; },[]);
  async function loadProfile(id:string){ const {data}=await supabase.from('profiles').select('*').eq('id',id).maybeSingle(); return data as Profile|null; }
  if(loading) return <div className="screen-center"><div className="loader"/><span>Loading your workspace…</span></div>;
  if(!session) return <Auth login={login} setLogin={setLogin} error={error} setError={setError}/>;
  return <Shell profile={profile} onLogout={()=>supabase.auth.signOut()}/>;
}

function Auth({login,setLogin,error,setError}:{login:boolean;setLogin:(v:boolean)=>void;error:string;setError:(v:string)=>void}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:any){e.preventDefault();setBusy(true);setError('');try{ if(login){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}else{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(data.user&&!data.session)setError('Account created. Check your email to confirm your account.');}}catch(err:any){setError(err.message||'Authentication failed.')}finally{setBusy(false)}}
 return <div className="auth-page"><div className="auth-glow"/><div className="auth-card"><div className="brand"><div className="brand-mark">E</div><div><b>EduFlow</b><span>School management, reimagined.</span></div></div><div className="eyebrow">SECURE WORKSPACE</div><h1>{login?'Welcome back':'Create your account'}</h1><p className="muted">{login?'Sign in to continue to your school workspace.':'Create an account to get started.'}</p><form onSubmit={submit}>{!login&&<Field label="Full name" value={name} onChange={setName} placeholder="Your full name"/>}<Field label="Email" value={email} onChange={setEmail} type="email" placeholder="you@example.com"/><Field label="Password" value={password} onChange={setPassword} type="password" placeholder="••••••••"/><button className="primary" disabled={busy}>{busy?'Please wait…':login?'Sign in':'Create account'}<ChevronRight size={17}/></button></form>{error&&<div className="alert">{error}</div>}<button className="text-button" onClick={()=>{setLogin(!login);setError('')}}>{login?'Need an account? Create one':'Already have an account? Sign in'}</button></div></div>
}
function Field({label,value,onChange,type='text',placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder:string}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} type={type} placeholder={placeholder} required/></label>}

function Shell({profile,onLogout}:{profile:Profile|null;onLogout:()=>void}){ const [active,setActive]=useState('dashboard');const [mobile,setMobile]=useState(false);const role=profile?.role||'admin'; const items=useMemo(()=>role==='super_admin'?nav:nav.filter(x=>x.id!=='admins'&&x.id!=='schools'),[role]); return <div className="app-shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="sidebar-head"><div className="brand-mark">E</div><div className="sidebar-name"><b>EduFlow</b><span>School OS</span></div><button className="icon-btn mobile-close" onClick={()=>setMobile(false)}><X size={19}/></button></div><div className="workspace"><span className="dot"/> {role.replace('_',' ')} workspace</div><nav>{items.map(item=>{const Icon=item.icon;return <button key={item.id} className={active===item.id?'nav-link active':'nav-link'} onClick={()=>{setActive(item.id);setMobile(false)}}><Icon size={18}/><span>{item.label}</span></button>})}</nav><div className="sidebar-bottom"><button className="nav-link" onClick={onLogout}><LogOut size={18}/><span>Sign out</span></button></div></aside><main className="main"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMobile(true)}><Menu size={21}/></button><div><div className="crumb">Workspace / {items.find(x=>x.id===active)?.label||'Dashboard'}</div><h1>{items.find(x=>x.id===active)?.label||'Dashboard'}</h1></div><div className="user"><div><b>{profile?.full_name||'Workspace Admin'}</b><span>{profile?.email||'Signed in'}</span></div><div className="avatar">{initials(profile?.full_name)}</div></div></header><div className="content">{active==='admins'&&role==='super_admin'?<AdminManagement/>:<Dashboard profile={profile} role={role}/>}</div></main></div> }

function Dashboard({profile,role}:{profile:Profile|null;role:Role}){const stats=role==='super_admin'?[['Schools','—'],['Admins','—'],['Students','—'],['Teachers','—']]:[['Students','—'],['Teachers','—'],['Attendance','—'],['Assignments','—']];return <><section className="hero"><div><div className="eyebrow">{role==='super_admin'?'PLATFORM OVERVIEW':'SCHOOL OVERVIEW'}</div><h2>Good to see you, {profile?.full_name?.split(' ')[0]||'there'}.</h2><p>Everything important for your school, in one calm workspace.</p></div><button className="primary small">Quick action <ChevronRight size={16}/></button></section><div className="stats">{stats.map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>Connect your data to see live metrics</small></div>)}</div><section className="grid-two"><div className="panel"><div className="panel-head"><div><h3>Getting started</h3><p>Build your school workspace step by step.</p></div><BookOpen size={20}/></div>{['Create your school profile','Add teachers and students','Set up classes and subjects','Start attendance and academic records'].map((x,i)=><div className="check-row" key={x}><div className={i===0?'check done':'check'}>{i===0?'✓':i+1}</div><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="panel"><div className="panel-head"><div><h3>Recent activity</h3><p>Your latest workspace events will appear here.</p></div><BarChart3 size={20}/></div><div className="empty"><div className="empty-icon"><BarChart3 size={22}/></div><b>No activity yet</b><span>Once your school is connected, important events will show here.</span></div></div></section></>}

function AdminManagement(){const [admins,setAdmins]=useState<Profile[]>([]);const [q,setQ]=useState('');const [busy,setBusy]=useState(true);const [show,setShow]=useState(false);useEffect(()=>{supabase.from('profiles').select('*').eq('role','admin').order('created_at',{ascending:false}).then(({data})=>{setAdmins((data||[]) as Profile[]);setBusy(false)})},[]);const filtered=admins.filter(a=>(a.full_name||'').toLowerCase().includes(q.toLowerCase())||(a.email||'').toLowerCase().includes(q.toLowerCase()));return <><div className="section-head"><div><div className="eyebrow">PLATFORM CONTROL</div><h2>Admin management</h2><p>Manage the people who operate each school.</p></div><button className="primary small" onClick={()=>setShow(true)}>+ Create admin</button></div><div className="stats compact"><div className="stat"><span>Total admins</span><strong>{admins.length}</strong><small>Platform accounts</small></div><div className="stat"><span>Active</span><strong>{admins.filter(x=>x.status!=='inactive').length}</strong><small>Currently enabled</small></div><div className="stat"><span>With school</span><strong>{admins.filter(x=>x.school_id).length}</strong><small>Associated tenants</small></div></div><div className="panel table-panel"><div className="table-tools"><div className="search"><Search size={17}/><input placeholder="Search admins…" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="muted">{filtered.length} admins</span></div>{busy?<div className="empty">Loading admins…</div>:filtered.length===0?<div className="empty"><div className="empty-icon"><Users size={22}/></div><b>No admins found</b><span>Create your first admin to begin.</span></div>:<div className="table-wrap"><table><thead><tr><th>Admin</th><th>Phone</th><th>Status</th><th>School</th><th>Created</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td><div className="person"><div className="avatar mini">{initials(a.full_name)}</div><div><b>{a.full_name||'Unnamed admin'}</b><span>{a.email||'—'}</span></div></div></td><td>{a.phone||'—'}</td><td><span className={a.status==='inactive'?'badge off':'badge'}>{a.status==='inactive'?'Inactive':'Active'}</span></td><td>{a.school_id?'Assigned':'Not created'}</td><td>{a.created_at?new Date(a.created_at).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div>}</div>{show&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h3>Create admin</h3><p>Account creation is securely handled by the server-side auth flow.</p></div><button className="icon-btn" onClick={()=>setShow(false)}><X size={19}/></button></div><div className="notice">The admin creation form is ready for the secure Edge Function integration. No service-role credentials are exposed in this app.</div><button className="primary" onClick={()=>setShow(false)}>Close</button></div></div>}</>}
